### ISSUE TITLE
Comparison to quantum elixir

### ISSUE THREAD

**Issue by venkatd** [SchedEx/SchedEx#1]
How does this compare to quantum-elixir? I'm currently using it in my project. SchedEx looks simpler and seems like it could accomplish the same thing.

**Comment by mtrudel** [comment]
Quantum was a huge inspiration for SchedEx, to be sure. It's a fine library and a great fit for many use cases. However there are quite a few things that set it and SchedEx apart.

In a nutshell, I think SchedEx's ethos of being the simplest thing that fits well into the larger OTP landscape is what makes it the more compelling option.

Broadly, we tried to design something more composeable and generally more 'OTP-ish' than Quantum, and as a result quite specifically didn't add any central notion of supervision or pooling into the design. We focused instead on making it easy to wire jobs sourced from SchedEx into the supervision model of your choice. What results is a much more flexible approach, and one that makes the resulting process hierarchy much more explicit. If you look at the first example in the [README](https://github.com/SchedEx/SchedEx) I think you'll see what I mean; the setup code for static jobs in SchedEx reads essentially in the same declarative style as Quantum's, though with greater flexibility and less ceremony. Jobs go directly from SchedEx into your application's Supervisor with nothing in between.

In addition, we had a functional requirement to be able to dynamically start and stop scheduled jobs at runtime. This is easily accomplished by an approach similar to the dynamic section of the README; the combination of crontabs in the database, SchedEx, and DynamicSupervisor yields an extremely powerful backend scheduling system with pretty minimal effort, never straying far from OTP idioms. 

Finally with respect to testability, we found Quantum's interface awkward to work with. SchedEx's time scale feature makes it easy to write tests that mirror the production environment in everything but the time scale, resulting in tests with near perfect parity to production. 

Hopefully this is a comprehensive answer. In the interest of tidiness I'll close this issue; please feel free to re-open if there's anything further.

**Comment by ghost** [comment]
@mtrudel Nice write-up that IMHO would have its place somewhere in the documentation.
