### ISSUE TITLE
Timex as an optional dependency?

### ISSUE THREAD

**Issue by venkatd** [SchedEx/SchedEx#11]
I like how lightweight SchedEx is but since I only need to work within the UTC timezone, I thought it would be nice to have Timex as an optional dependency only when you need to deal with timezones.

Is this doable? If so, I can submit a PR for this.

```
├── timex ~> 3.4 (Hex package)
│   ├── combine ~> 0.10 (Hex package)
│   ├── gettext ~> 0.10 (Hex package)
│   └── tzdata ~> 0.1.8 or ~> 0.5 (Hex package)
│       └── hackney ~> 1.0 (Hex package)
│           ├── certifi 2.4.2 (Hex package)
│           │   └── parse_trans ~>3.3 (Hex package)
│           ├── idna 6.0.0 (Hex package)
│           │   └── unicode_util_compat 0.4.1 (Hex package)
│           ├── metrics 1.0.1 (Hex package)
│           ├── mimerl 1.0.2 (Hex package)
│           └── ssl_verify_fun 1.1.4 (Hex package)
```

**Comment by mtrudel** [comment]
So long as usage remains backwards compatible, I have no problem with that and would happily take a PR. Thanks!

**Comment by mtrudel** [comment]
Closing this issue since the next step would be a separate PR anyway.
