### ISSUE TITLE
run_in not working

### ISSUE THREAD

**Issue by cultofmetatron** [SchedEx/SchedEx#14]
I'm using run_in/2 to schedule a delayed task 

```elixir
timeout = 5000
          status = SchedEx.run_in(fn ->
            IO.puts("Running the close task on order  cycle: #{order_cycle.id}")
            order_cycle = Repo.get(Restaurant.OrderCycle, order_cycle_id)

            unless order_cycle.is_closed do
              result = set_order_cycle_to_closed(user, restaurant_id, order_cycle_id)
              IO.puts("generating close, logging result: >")
              IO.inspect(result)
            end

            {:ok, :boomer}
          end, timeout)

          IO.puts("timing status >")
          IO.inspect(status)
```

Timing status shows `{:ok, #PID<0.893.0>}` which indicates no error in queuing up the function but the line ` IO.puts("Running the close task on order  cycle: #{order_cycle.id}")` never runs indicating that the function is not being run in 5 seconds.

could it be because I'm running this in a docker container? I don't think it is as elixir scheduler runs within the vm process but its the only straw I have to grasp atm

as far as I know, run_in doesn't require anything being mounted in the supervisor tree. please let me know if thats an incorrect assumption but I saw nothing to that effect in the docs

**Comment by mtrudel** [comment]
`{:ok, :boomer}` 😆 

I just verified that things work as expected on HEAD:

```elixir
iex(3)> timeout = 5000
5000
iex(4)> status = SchedEx.run_in(fn -> IO.puts("Hello") end, timeout)
{:ok, #PID<0.1718.0>}
Hello
iex(5)> {:ok, pid} = status
{:ok, #PID<0.1718.0>}
iex(6)> Process.alive? pid
false
```
which is very much what I would expect for both HEAD and all previous releases (this is obviously core functionality and well under test). 

I would suspect it's likely a supervision tree issue as you mentioned. Bear in mind that SchedEx processes do not do any supervision internally, and are linked to the calling process. As a result, SchedEx processes only live as long as the original calling process. I strongly suspect that the calling process is completing before the timer in question is fired. 

Closing this issue as there's likely nothing further to do on the code side of things for this issue. If you're still having issues, please comment here (or hit me up on #sched_ex in the Elixir Slack) for more help.

Thanks for the issue!

**Comment by cultofmetatron** [comment]
> SchedEx processes only live as long as the original calling process. 


ok that would explain it. The scheduling is done in a http response handler and that terminates when the response is finished. will message you on the slack for what an alternative way of doing that would be
