### ISSUE TITLE
Question: Does SchedEx handles well DST changes?

### ISSUE THREAD

**Issue by codeadict** [SchedEx/SchedEx#6]
Hi guys, thanks for the great package, not an issue really but just wanted to ask how `SchedEx` handles DST changes, I see there are some tests for it but wanted to know how is it implemented or if it is handled by Timex or a third party package. Feel free to close this issue after responding.

**Comment by mtrudel** [comment]
It's mostly handled by Timex, with a [small bit of policy in SchedEx](https://github.com/SchedEx/SchedEx/blob/master/lib/sched_ex/runner.ex#L131) to handle ambiguous dates as a result of a recurrence landing within a DST transition (if there are two possible dates as a result of a DST transition, SchedEx will choose the later one).

**Comment by codeadict** [comment]
Thanks so much for the quick response
